version: "3.9"

networks:
  app:

services:
  app:
    build:
      context: ./.docker/php-fpm
      dockerfile: dockerfile
    image: app-package
    container_name: app-package
    working_dir: /var/www
    volumes:
      - ./:/var/www
    restart: unless-stopped
    networks:
      - app

  composer:
    build:
      context: ./.docker/composer
      dockerfile: dockerfile
    image: composer-package
    container_name: composer-package
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: ["composer"]
    networks:
      - app